function Tout = trap_phase_join_on_id(T_rein, T_with, ids)
    if isempty(ids)
        Tout = table([], [], [], [], [], [], ...
            'VariableNames', {'id', 'region', 'q_Reinstatement', 'meanAct_minus_Pas_Rein', ...
            'q_Withdrawal', 'meanAct_minus_Pas_With'});
        return;
    end
    [~, ia] = ismember(ids, T_rein.id);
    [~, ib] = ismember(ids, T_with.id);
    Tout = table(ids, T_rein.region(ia), T_rein.q_AP(ia), T_rein.mean_Active_minus_Passive(ia), ...
        T_with.q_AP(ib), T_with.mean_Active_minus_Passive(ib), ...
        'VariableNames', {'id', 'region', 'q_Reinstatement', 'meanAct_minus_Pas_Rein', ...
        'q_Withdrawal', 'meanAct_minus_Pas_With'});
end
