function trap_write_AP_shared_evidence_csv(T_rein, T_with, ids, csvPath)
% One row per region id: means + p for Reinstatement and Withdrawal separately.
    if isempty(ids)
        writetable(table([], [], [], [], [], [], [], [], 'VariableNames', ...
            {'id', 'region', 'mean_Active_Rein', 'mean_Passive_Rein', 'p_Rein', ...
            'mean_Active_With', 'mean_Passive_With', 'p_With'}), csvPath);
        return;
    end
    idv = ids(:);
    [tf, ir] = ismember(idv, T_rein.id);
    [~, iw] = ismember(idv, T_with.id);
    Tout = table(idv(tf), T_rein.region(ir(tf)), ...
        T_rein.mean_Active(ir(tf)), T_rein.mean_Passive(ir(tf)), T_rein.p_AP(ir(tf)), ...
        T_with.mean_Active(iw(tf)), T_with.mean_Passive(iw(tf)), T_with.p_AP(iw(tf)), ...
        'VariableNames', {'id', 'region', 'mean_Active_Reinstatement', 'mean_Passive_Reinstatement', ...
        'p_Act_vs_Pas_Reinstatement', 'mean_Active_Withdrawal', 'mean_Passive_Withdrawal', ...
        'p_Act_vs_Pas_Withdrawal'});
    writetable(Tout, csvPath);
end
